### ISSUE TITLE
Recieving instead of Sending

### ISSUE THREAD

**Issue by TCWORLD** [cpldcpu/u-wire#1]
Hi,

I wonder if it would be possible to modify this to send data back to the computer instead of the other way around.
I can see such a thing being very useful - maybe a tiny data logger, or to connect a one-wire temp sensor.  Could even get it to enumerate under the HID class as a keyboard and have it send keystrokes.

I have quite a bit of experience making code as small as possible (and writing in assembler), and with V-USB (modified the HIDSerial repository to fit into an attiny2313 as a USB-USART adapter), so I don't mind doing the coding for such an idea, but I am interested in your opinion as it would depend on how you have modified VUSB - presumably you've removed a large amount of stuff from it.

**Comment by cpldcpu** [comment]
Well yes, in principle that would be possible. However, the applications would be fairly limited due to the lack of remaining SRAM.

Actually, little-wire already supports this kind of functionality. It would be easier to use that as a starting point.
