### ISSUE TITLE
Win7 x64 problems

### ISSUE THREAD

**Issue by Gamadril** [cpldcpu/u-wire#2]
Have you ever tried it on Windows 7 x64? If I connect the usb device, it's shown as an unknown device. Not because of the driver - it's not recognized at all. VID and PID are 0000. On Windows XP 32 bit there are no problems, OSX is also happy

**Comment by cpldcpu** [comment]
I have developed it using Win7 x64, so the difference in operating systems is a bit puzzling to me. Do any other little wire devices work?

**Comment by Gamadril** [comment]
Sadly no, I'll try it on another Win7 x64 machine just to be sure...

**Comment by cpldcpu** [comment]
Well, the entire thing is pretty hacky. It should not be very surprising that there are some rough edges. For example it could also be possible that the oscillator tuning does not work on the pc for some reason. The only way to really debug it would be to log the USB traffic. But I am not sure it is worth it for this hack.

**Comment by Gamadril** [comment]
Well, I would call it a "masterpiece of minification and optimization" :-) Actually I just wanted to check if [that](https://github.com/Gamadril/u-wire-control) works with µ-wire on Win7 x64. Could you test it? It didn't work with libUSB drivers on WinXP, so I had to take libusbK (put them [here](https://github.com/Gamadril/u-wire/tree/master/driver/windows))

**Comment by cpldcpu** [comment]
Thanks :) Thats's an interesting app, going to check it out. 

I was not aware of the diamex WS2812 Tester. Seems I should add proper license terms to the repository. Anyhow, going to close this.
